[colors]
foreground = "#DCD7BA"
background = "#1F1F28"
cursor_bg = "#c8c093"
cursor_border = "#c8c093"
cursor_fg = "#1f1f28"
selection_bg = "#658594"
selection_fg = "#c8c093"
scrollbar_thumb = "#393836"
split = "#8992a7"

ansi = [
  "#0d0c0c",
  "#c4746e",
  "#8a9a7b",
  "#c4b28a",
  "#8ba4b0",
  "#a292a3",
  "#8ea4a2",
  "#C8C093",
]
brights = [
  "#a6a69c",
  "#E46876",
  "#87a987",
  "#E6C384",
  "#7FB4CA",
  "#938AA9",
  "#7AA89F",
  "#c5c9c5",
]

[colors.tab_bar]
inactive_tab_edge = "#393836"
background = "#1F1F28"

[colors.tab_bar.active_tab]
fg_color = "#C8C093"
bg_color = "#1F1F28"

[colors.tab_bar.inactive_tab]
fg_color = "#a6a69c"
bg_color = "#393836"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#DCD7BA"
bg_color = "#393836"

[colors.tab_bar.new_tab_hover]
fg_color = "#DCD7BA"
bg_color = "#1F1F28"

[colors.tab_bar.new_tab]
fg_color = "#DCD7BA"
bg_color = "#1F1F28"

[metadata]
aliases = []
author = "rebelot"
name = "kanagawa_paper"
