[colors]
ansi = [
    '#22212C',
    '#FF9580',
    '#8AFF80',
    '#FFFF80',
    '#9580FF',
    '#FF80BF',
    '#80FFEA',
    '#F8F8F2',
]
background = '#0B0D0F'
brights = [
    '#364049',
    '#FFAA99',
    '#A2FF99',
    '#FFFF99',
    '#AA99FF',
    '#FF99CC',
    '#99FFEE',
    '#FFFFFF',
]
compose_cursor = '#FFCA80'
cursor_bg = '#708CA9'
cursor_border = '#708CA9'
cursor_fg = '#0B0D0F'
foreground = '#F8F8F2'
scrollbar_thumb = '#414D58'
selection_bg = '#414D58'
selection_fg = '#F8F8F2'
split = '#708CA9'

[colors.indexed]

[colors.tab_bar]
background = '#708CA9'
inactive_tab_edge = 'none'

[colors.tab_bar.active_tab]
bg_color = '#708CA9'
fg_color = '#0B0D0F'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#0B0D0F'
fg_color = '#708CA9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#414D58'
fg_color = '#F8F8F2'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#0B0D0F'
fg_color = '#708CA9'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#FF80BF'
fg_color = '#0B0D0F'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[metadata]
author = 'ispern'
name = 'MyTheme'
